service: shirokuro_backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11

plugins:
  - serverless-offline

functions:
  hello:
    handler: src.apps.lambda.iam.account.account_creator_put_controller.account_create_aws_post_controller
    events:
      - httpApi:
          path: /
          method: PUT
